name: Secured Docker Go Calc v4

on: 
    workflow_dispatch:
        
jobs:
    build:
        name: Build image and push to Docker Hub
        runs-on: ubuntu-latest

        steps:
            - # This step checks out the repository so that the workflow can access its contents.
                name: Checkout repository
                uses: actions/checkout@v4

            - # This step sets up Docker Buildx, which is a Docker CLI plugin for extended build capabilities with BuildKit.
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            
            - # This step sets up QEMU, which allows building multi-platform Docker images.
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            
            - # This step logs in to Docker Hub using the credentials stored in GitHub Secrets.
                name: Log in to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            
            - # Build Docker image
                name: Build Docker image
                run: |
                    docker buildx build \
                        --load \
                        --tag ${{ secrets.DOCKERHUB_USERNAME }}/secured-go:calcV4 \
                        --tag ${{ secrets.DOCKERHUB_USERNAME }}/secured-go:latest \
                        --cache-from=type=gha \
                        --cache-to=type=gha,mode=max \
                        --platform=linux/arm64 \
                        .
                # --load tells Builx to load the image into the local Docker deamon after building it.
            
            - # This step builds and pushes the Docker image to Docker Hub. It uses the docker/build-push-action to build the image, push it to the registry, and cache layers for faster builds.
                name: Push Docker image to Docker Hub
                run: |
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/secured-go:calcV4
                    docker push ${{ secrets.DOCKERHUB_USERNAME }}/secured-go:latest
