name: Scan for CVEs using Snyk

on:
    workflow_dispatch:

jobs:
    cve-scan:
        name: Scan for CVEs
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout repository
                uses: actions/checkout@v4
            # Scanning the docker image for vulnearbilities with Snyk
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Security scan with Snyk
                uses: snyk/actions/docker@master
                id: snyk-docker-scan
                continue-on-error: true
                env:
                    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
                with:
                    image: ${{ secrets.DOCKERHUB_USERNAME }}/secured-go
                    args: |
                        --file./Dockerfile --severity-threshold=high
                        --sarif-file-output=./security/snyk-report.snyk.sarif
                    sarif: true

            -
                name: Run Snyk test
                run: snyk test --all-projects --fall-on=all --json-file-output=snyk-report.json
