---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swcalc-deployment
  labels:
    app: swcalc
spec:
  replicas: 5
  selector:
    matchLabels:
      app: swcalc
  template:
    metadata:
      labels:
        app: swcalc
    spec:
      containers:
        - name: swcalc
          image: robinrobinson/secured-go:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 128Mi
              cpu: 200m
