apiVersion: v1
kind: Service
metadata:
  name: swcalc-loadbalancer
  labels:
    app: swcalc
spec:
  type: LoadBalancer
  selector:
    app: swcalc
  ports:
  -
    name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
