---
# ClusterIP service for the application
apiVersion: v1
kind: Service
metadata:
  name: swcalc-service
  labels:
    app: swcalc
spec:
  type: ClusterIP
  selector:
    app: swcalc
  ports:
    -
      name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
...