name: Secured Docker Go Page

on: workflow_dispatch

jobs:
    build:
        name: Build image and push to Docker Hub
        runs-on: ubuntu-latest

        steps:
            -
                name: Checkout repo
                uses: actions/checkout@v4
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v3
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v3
            -
                name: Log in to Docker Hub
                uses: docker/login-action@v3
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push Docker image
                uses: docker/build-push-action@v6
                with:
                    push: true
                    tags: ${{ secrets.DOCKERHUB_USERNAME }}/secured-go:${{ github.run_id }}
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
                    platforms: linux/amd64, linux/arm64
